services:
  vue-template:
    image: mcr.microsoft.com/devcontainers/typescript-node:${NODE_VERSION}-bookworm
    volumes:
      - ${PNPM_STORE_PATH}/.cache/pnpm-store:/root/.pnpm-store:cached
      - ../:/workspace
      - /home/sleepyhead/Code/:/Code
    env_file:
      - .env
    network_mode: host
    stdin_open: true
    tty: true
